package com.amsoftgroup.geospatial.dc.hibernate;

// Generated Jan 8, 2012 5:37:14 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlRootElement;

import com.amsoftgroup.geospatial.dc.business.Entity;

/**
 * Embassy generated by hbm2java
 */
@XmlRootElement
public class Embassy extends Entity {

	private int gid;
	private String country;
	private String address;
	private String city;
	private String state;
	private String telephone;
	private String embTitle;
	private String weburl;
	private String gisId;
	private BigDecimal x;
	private BigDecimal y;
	private Long addrid;
	//private Serializable theGeom;

	public Embassy() {
	}

	public Embassy(int gid) {
		this.gid = gid;
	}

	public Embassy(int gid, String country, String address, String city,
			String state, String telephone, String embTitle, String weburl,
			String gisId, BigDecimal x, BigDecimal y, Long addrid,
			Serializable theGeom) {
		this.gid = gid;
		this.country = country;
		this.address = address;
		this.city = city;
		this.state = state;
		this.telephone = telephone;
		this.embTitle = embTitle;
		this.weburl = weburl;
		this.gisId = gisId;
		this.x = x;
		this.y = y;
		this.addrid = addrid;
	//	this.theGeom = theGeom;
	}

	public int getGid() {
		return this.gid;
	}

	public void setGid(int gid) {
		this.gid = gid;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getEmbTitle() {
		return this.embTitle;
	}

	public void setEmbTitle(String embTitle) {
		this.embTitle = embTitle;
	}

	public String getWeburl() {
		return this.weburl;
	}

	public void setWeburl(String weburl) {
		this.weburl = weburl;
	}

	public String getGisId() {
		return this.gisId;
	}

	public void setGisId(String gisId) {
		this.gisId = gisId;
	}

	public BigDecimal getX() {
		return this.x;
	}

	public void setX(BigDecimal x) {
		this.x = x;
	}

	public BigDecimal getY() {
		return this.y;
	}

	public void setY(BigDecimal y) {
		this.y = y;
	}

	public Long getAddrid() {
		return this.addrid;
	}

	public void setAddrid(Long addrid) {
		this.addrid = addrid;
	}
/*
	public Serializable getTheGeom() {
		return this.theGeom;
	}

	public void setTheGeom(Serializable theGeom) {
		this.theGeom = theGeom;
	}
*/
}
