package com.amsoftgroup.geospatial.dc.hibernate;

// Generated Jan 8, 2012 5:37:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Entityquery generated by hbm2java
 */
public class Entityquery implements java.io.Serializable {

	private int entityId;
	private String entityDescription;
	private String table;
	private String source;
	private Date datePublished;
	private Date dateUploaded;
	private String format;
	private String shapefileTitle;

	public Entityquery() {
	}

	public Entityquery(int entityId, String entityDescription) {
		this.entityId = entityId;
		this.entityDescription = entityDescription;
	}

	public Entityquery(int entityId, String entityDescription, String table,
			String source, Date datePublished, Date dateUploaded,
			String format, String shapefileTitle) {
		this.entityId = entityId;
		this.entityDescription = entityDescription;
		this.table = table;
		this.source = source;
		this.datePublished = datePublished;
		this.dateUploaded = dateUploaded;
		this.format = format;
		this.shapefileTitle = shapefileTitle;
	}

	public int getEntityId() {
		return this.entityId;
	}

	public void setEntityId(int entityId) {
		this.entityId = entityId;
	}

	public String getEntityDescription() {
		return this.entityDescription;
	}

	public void setEntityDescription(String entityDescription) {
		this.entityDescription = entityDescription;
	}

	public String getTable() {
		return this.table;
	}

	public void setTable(String table) {
		this.table = table;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public Date getDatePublished() {
		return this.datePublished;
	}

	public void setDatePublished(Date datePublished) {
		this.datePublished = datePublished;
	}

	public Date getDateUploaded() {
		return this.dateUploaded;
	}

	public void setDateUploaded(Date dateUploaded) {
		this.dateUploaded = dateUploaded;
	}

	public String getFormat() {
		return this.format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	public String getShapefileTitle() {
		return this.shapefileTitle;
	}

	public void setShapefileTitle(String shapefileTitle) {
		this.shapefileTitle = shapefileTitle;
	}

}
