package com.amsoftgroup.geospatial.dc.hibernate;

// Generated Jan 8, 2012 5:37:14 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Grocerystores generated by hbm2java
 */
@XmlRootElement
public class Grocerystores implements java.io.Serializable {

	private int gid;
	private String storename;
	private String address;
	private String phone;
	private String present90;
	private String present95;
	private String present00;
	private String present05;
	private String present08;
	private String notes;
	private String cleanaddr;
	private BigDecimal XCoord;
	private BigDecimal YCoord;
	private String matchtype;
	private Long addressId;
	private Integer ward;
	private String present09;
	private String present10;
	private String present11;
	private String present12;
	//private Serializable theGeom;

	public Grocerystores() {
	}

	public Grocerystores(int gid) {
		this.gid = gid;
	}

	public Grocerystores(int gid, String storename, String address,
			String phone, String present90, String present95,
			String present00, String present05, String present08, String notes,
			String cleanaddr, BigDecimal XCoord, BigDecimal YCoord,
			String matchtype, Long addressId, Integer ward, String present09,
			String present10, String present11, String present12,
			Serializable theGeom) {
		this.gid = gid;
		this.storename = storename;
		this.address = address;
		this.phone = phone;
		this.present90 = present90;
		this.present95 = present95;
		this.present00 = present00;
		this.present05 = present05;
		this.present08 = present08;
		this.notes = notes;
		this.cleanaddr = cleanaddr;
		this.XCoord = XCoord;
		this.YCoord = YCoord;
		this.matchtype = matchtype;
		this.addressId = addressId;
		this.ward = ward;
		this.present09 = present09;
		this.present10 = present10;
		this.present11 = present11;
		this.present12 = present12;
		//this.theGeom = theGeom;
	}

	public int getGid() {
		return this.gid;
	}

	public void setGid(int gid) {
		this.gid = gid;
	}

	public String getStorename() {
		return this.storename;
	}

	public void setStorename(String storename) {
		this.storename = storename;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String string) {
		this.phone = string;
	}

	public String getPresent90() {
		return this.present90;
	}

	public void setPresent90(String present90) {
		this.present90 = present90;
	}

	public String getPresent95() {
		return this.present95;
	}

	public void setPresent95(String present95) {
		this.present95 = present95;
	}

	public String getPresent00() {
		return this.present00;
	}

	public void setPresent00(String present00) {
		this.present00 = present00;
	}

	public String getPresent05() {
		return this.present05;
	}

	public void setPresent05(String present05) {
		this.present05 = present05;
	}

	public String getPresent08() {
		return this.present08;
	}

	public void setPresent08(String present08) {
		this.present08 = present08;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getCleanaddr() {
		return this.cleanaddr;
	}

	public void setCleanaddr(String cleanaddr) {
		this.cleanaddr = cleanaddr;
	}

	public BigDecimal getXCoord() {
		return this.XCoord;
	}

	public void setXCoord(BigDecimal XCoord) {
		this.XCoord = XCoord;
	}

	public BigDecimal getYCoord() {
		return this.YCoord;
	}

	public void setYCoord(BigDecimal YCoord) {
		this.YCoord = YCoord;
	}

	public String getMatchtype() {
		return this.matchtype;
	}

	public void setMatchtype(String matchtype) {
		this.matchtype = matchtype;
	}

	public Long getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Long addressId) {
		this.addressId = addressId;
	}

	public Integer getWard() {
		return this.ward;
	}

	public void setWard(Integer ward) {
		this.ward = ward;
	}

	public String getPresent09() {
		return this.present09;
	}

	public void setPresent09(String present09) {
		this.present09 = present09;
	}

	public String getPresent10() {
		return this.present10;
	}

	public void setPresent10(String present10) {
		this.present10 = present10;
	}

	public String getPresent11() {
		return this.present11;
	}

	public void setPresent11(String present11) {
		this.present11 = present11;
	}

	public String getPresent12() {
		return this.present12;
	}

	public void setPresent12(String present12) {
		this.present12 = present12;
	}
/*
	public Serializable getTheGeom() {
		return this.theGeom;
	}

	public void setTheGeom(Serializable theGeom) {
		this.theGeom = theGeom;
	}
*/
}
