package com.amsoftgroup.geospatial.dc.hibernate;

// Generated Jan 8, 2012 5:37:14 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Hikingtrails generated by hbm2java
 */
@XmlRootElement
public class Hikingtrails implements java.io.Serializable {

	private int gid;
	private Long objectid;
	private BigDecimal length;
	private String street;
	private Long aadtNum;
	private Long buffer;
	private BigDecimal laneWidth;
	private BigDecimal adtLane;
	private BigDecimal rdWidth;
	private String name;
	private String facilityN;
	private String status;
	private String surface;
	private String width;
	private String maintenanc;
	private BigDecimal shapeLen;
	//private Serializable theGeom;

	public Hikingtrails() {
	}

	public Hikingtrails(int gid) {
		this.gid = gid;
	}

	public Hikingtrails(int gid, Long objectid, BigDecimal length,
			String street, Long aadtNum, Long buffer, BigDecimal laneWidth,
			BigDecimal adtLane, BigDecimal rdWidth, String name,
			String facilityN, String status, String surface, String width,
			String maintenanc, BigDecimal shapeLen, Serializable theGeom) {
		this.gid = gid;
		this.objectid = objectid;
		this.length = length;
		this.street = street;
		this.aadtNum = aadtNum;
		this.buffer = buffer;
		this.laneWidth = laneWidth;
		this.adtLane = adtLane;
		this.rdWidth = rdWidth;
		this.name = name;
		this.facilityN = facilityN;
		this.status = status;
		this.surface = surface;
		this.width = width;
		this.maintenanc = maintenanc;
		this.shapeLen = shapeLen;
		//this.theGeom = theGeom;
	}

	public int getGid() {
		return this.gid;
	}

	public void setGid(int gid) {
		this.gid = gid;
	}

	public Long getObjectid() {
		return this.objectid;
	}

	public void setObjectid(Long objectid) {
		this.objectid = objectid;
	}

	public BigDecimal getLength() {
		return this.length;
	}

	public void setLength(BigDecimal length) {
		this.length = length;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public Long getAadtNum() {
		return this.aadtNum;
	}

	public void setAadtNum(Long aadtNum) {
		this.aadtNum = aadtNum;
	}

	public Long getBuffer() {
		return this.buffer;
	}

	public void setBuffer(Long buffer) {
		this.buffer = buffer;
	}

	public BigDecimal getLaneWidth() {
		return this.laneWidth;
	}

	public void setLaneWidth(BigDecimal laneWidth) {
		this.laneWidth = laneWidth;
	}

	public BigDecimal getAdtLane() {
		return this.adtLane;
	}

	public void setAdtLane(BigDecimal adtLane) {
		this.adtLane = adtLane;
	}

	public BigDecimal getRdWidth() {
		return this.rdWidth;
	}

	public void setRdWidth(BigDecimal rdWidth) {
		this.rdWidth = rdWidth;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFacilityN() {
		return this.facilityN;
	}

	public void setFacilityN(String facilityN) {
		this.facilityN = facilityN;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getSurface() {
		return this.surface;
	}

	public void setSurface(String surface) {
		this.surface = surface;
	}

	public String getWidth() {
		return this.width;
	}

	public void setWidth(String width) {
		this.width = width;
	}

	public String getMaintenanc() {
		return this.maintenanc;
	}

	public void setMaintenanc(String maintenanc) {
		this.maintenanc = maintenanc;
	}

	public BigDecimal getShapeLen() {
		return this.shapeLen;
	}

	public void setShapeLen(BigDecimal shapeLen) {
		this.shapeLen = shapeLen;
	}
/*
	public Serializable getTheGeom() {
		return this.theGeom;
	}

	public void setTheGeom(Serializable theGeom) {
		this.theGeom = theGeom;
	}
*/
}
