package com.amsoftgroup.geospatial.dc.hibernate;

// Generated Jan 8, 2012 5:37:14 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Historicdistricts generated by hbm2java
 */
@XmlRootElement
public class Historicdistricts implements java.io.Serializable {

	private int gid;
	private Integer objectId;
	private String gisId;
	private String name;
	private String webUrl;
	//private Serializable theGeom;

	public Historicdistricts() {
	}

	public Historicdistricts(int gid) {
		this.gid = gid;
	}

	public Historicdistricts(int gid, Integer objectId, String gisId,
			String name, String webUrl, Serializable theGeom) {
		this.gid = gid;
		this.objectId = objectId;
		this.gisId = gisId;
		this.name = name;
		this.webUrl = webUrl;
		//this.theGeom = theGeom;
	}

	public int getGid() {
		return this.gid;
	}

	public void setGid(int gid) {
		this.gid = gid;
	}

	public Integer getObjectId() {
		return this.objectId;
	}

	public void setObjectId(Integer objectId) {
		this.objectId = objectId;
	}

	public String getGisId() {
		return this.gisId;
	}

	public void setGisId(String gisId) {
		this.gisId = gisId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getWebUrl() {
		return this.webUrl;
	}

	public void setWebUrl(String webUrl) {
		this.webUrl = webUrl;
	}
/*
	public Serializable getTheGeom() {
		return this.theGeom;
	}

	public void setTheGeom(Serializable theGeom) {
		this.theGeom = theGeom;
	}
*/
}
