package com.amsoftgroup.geospatial.dc.hibernate;

// Generated Jan 8, 2012 5:37:14 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Historicstructures generated by hbm2java
 */
@XmlRootElement
public class Historicstructures implements java.io.Serializable {

	private int gid;
	private String gisId;
	private String name;
	private String label;
	private String address;
	private String ssl;
	private String historical;
	private String eligibilit;
	private String type;
	private BigDecimal shapeLeng;
	private BigDecimal shapeArea;
	//private Serializable theGeom;

	public Historicstructures() {
	}

	public Historicstructures(int gid) {
		this.gid = gid;
	}

	public Historicstructures(int gid, String gisId, String name, String label,
			String address, String ssl, String historical, String eligibilit,
			String type, BigDecimal shapeLeng, BigDecimal shapeArea,
			Serializable theGeom) {
		this.gid = gid;
		this.gisId = gisId;
		this.name = name;
		this.label = label;
		this.address = address;
		this.ssl = ssl;
		this.historical = historical;
		this.eligibilit = eligibilit;
		this.type = type;
		this.shapeLeng = shapeLeng;
		this.shapeArea = shapeArea;
		//this.theGeom = theGeom;
	}

	public int getGid() {
		return this.gid;
	}

	public void setGid(int gid) {
		this.gid = gid;
	}

	public String getGisId() {
		return this.gisId;
	}

	public void setGisId(String gisId) {
		this.gisId = gisId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getSsl() {
		return this.ssl;
	}

	public void setSsl(String ssl) {
		this.ssl = ssl;
	}

	public String getHistorical() {
		return this.historical;
	}

	public void setHistorical(String historical) {
		this.historical = historical;
	}

	public String getEligibilit() {
		return this.eligibilit;
	}

	public void setEligibilit(String eligibilit) {
		this.eligibilit = eligibilit;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public BigDecimal getShapeLeng() {
		return this.shapeLeng;
	}

	public void setShapeLeng(BigDecimal shapeLeng) {
		this.shapeLeng = shapeLeng;
	}

	public BigDecimal getShapeArea() {
		return this.shapeArea;
	}

	public void setShapeArea(BigDecimal shapeArea) {
		this.shapeArea = shapeArea;
	}
/*
	public Serializable getTheGeom() {
		return this.theGeom;
	}

	public void setTheGeom(Serializable theGeom) {
		this.theGeom = theGeom;
	}
*/
}
