package com.amsoftgroup.geospatial.dc.hibernate;

// Generated Jan 8, 2012 5:37:14 PM by Hibernate Tools 3.4.0.CR1


import javax.xml.bind.annotation.XmlRootElement;

/**
 * Hospitals generated by hbm2java
 */
@XmlRootElement
public class Hospitals  {

	private int gid;
	private String gisId;
	private String name;
	private String address;
	private String ssl;
	private String webUrl;
	private String type;
	private Long aid;
	private String adultMedi;
	private String adultMino;
	private String adultMajo;
	private String criticalB;
	private String obstetrics;
	private String pediatric;
	private String pediatric1;
	private String pediatri1;
//	private Serializable theGeom;

	public Hospitals() {
	}

	public Hospitals(int gid) {
		this.gid = gid;
	}

	public Hospitals(int gid, String gisId, String name, String address,
			String ssl, String webUrl, String type, Long aid, String adultMedi,
			String adultMino, String adultMajo, String criticalB,
			String obstetrics, String pediatric, String pediatric1,
			String pediatri1) {
		this.gid = gid;
		this.gisId = gisId;
		this.name = name;
		this.address = address;
		this.ssl = ssl;
		this.webUrl = webUrl;
		this.type = type;
		this.aid = aid;
		this.adultMedi = adultMedi;
		this.adultMino = adultMino;
		this.adultMajo = adultMajo;
		this.criticalB = criticalB;
		this.obstetrics = obstetrics;
		this.pediatric = pediatric;
		this.pediatric1 = pediatric1;
		this.pediatri1 = pediatri1;

	}

	public int getGid() {
		return this.gid;
	}

	public void setGid(int gid) {
		this.gid = gid;
	}

	public String getGisId() {
		return this.gisId;
	}

	public void setGisId(String gisId) {
		this.gisId = gisId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getSsl() {
		return this.ssl;
	}

	public void setSsl(String ssl) {
		this.ssl = ssl;
	}

	public String getWebUrl() {
		return this.webUrl;
	}

	public void setWebUrl(String webUrl) {
		this.webUrl = webUrl;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Long getAid() {
		return this.aid;
	}

	public void setAid(Long aid) {
		this.aid = aid;
	}

	public String getAdultMedi() {
		return this.adultMedi;
	}

	public void setAdultMedi(String adultMedi) {
		this.adultMedi = adultMedi;
	}

	public String getAdultMino() {
		return this.adultMino;
	}

	public void setAdultMino(String adultMino) {
		this.adultMino = adultMino;
	}

	public String getAdultMajo() {
		return this.adultMajo;
	}

	public void setAdultMajo(String adultMajo) {
		this.adultMajo = adultMajo;
	}

	public String getCriticalB() {
		return this.criticalB;
	}

	public void setCriticalB(String criticalB) {
		this.criticalB = criticalB;
	}

	public String getObstetrics() {
		return this.obstetrics;
	}

	public void setObstetrics(String obstetrics) {
		this.obstetrics = obstetrics;
	}

	public String getPediatric() {
		return this.pediatric;
	}

	public void setPediatric(String pediatric) {
		this.pediatric = pediatric;
	}

	public String getPediatric1() {
		return this.pediatric1;
	}

	public void setPediatric1(String pediatric1) {
		this.pediatric1 = pediatric1;
	}

	public String getPediatri1() {
		return this.pediatri1;
	}

	public void setPediatri1(String pediatri1) {
		this.pediatri1 = pediatri1;
	}


}
