package com.amsoftgroup.geospatial.dc.hibernate;

// Generated Jan 8, 2012 5:37:14 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Hotels generated by hbm2java
 */
@XmlRootElement
public class Hotels implements java.io.Serializable {

	private int gid;
	private BigDecimal objectid;
	private String webUrl;
	private String phone;
	private String zip;
	private String gisId;
	private String address;
	private int numrooms;
	private String name;
	private BigDecimal x;
	private BigDecimal y;
	private BigDecimal addrid;
	//private Serializable theGeom;

	public Hotels() {
	}

	public Hotels(int gid) {
		this.gid = gid;
	}

	public Hotels(int gid, BigDecimal objectid, String webUrl, String phone,
			String zip, String gisId, String address, int numrooms,
			String name, BigDecimal x, BigDecimal y, BigDecimal addrid,
			Serializable theGeom) {
		this.gid = gid;
		this.objectid = objectid;
		this.webUrl = webUrl;
		this.phone = phone;
		this.zip = zip;
		this.gisId = gisId;
		this.address = address;
		this.numrooms = numrooms;
		this.name = name;
		this.x = x;
		this.y = y;
		this.addrid = addrid;
		//this.theGeom = theGeom;
	}

	public int getGid() {
		return this.gid;
	}

	public void setGid(int gid) {
		this.gid = gid;
	}

	public BigDecimal getObjectid() {
		return this.objectid;
	}

	public void setObjectid(BigDecimal objectid) {
		this.objectid = objectid;
	}

	public String getWebUrl() {
		return this.webUrl;
	}

	public void setWebUrl(String webUrl) {
		this.webUrl = webUrl;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getGisId() {
		return this.gisId;
	}

	public void setGisId(String gisId) {
		this.gisId = gisId;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public int getNumrooms() {
		return this.numrooms;
	}

	public void setNumrooms(int i) {
		this.numrooms = i;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getX() {
		return this.x;
	}

	public void setX(BigDecimal x) {
		this.x = x;
	}

	public BigDecimal getY() {
		return this.y;
	}

	public void setY(BigDecimal y) {
		this.y = y;
	}

	public BigDecimal getAddrid() {
		return this.addrid;
	}

	public void setAddrid(BigDecimal addrid) {
		this.addrid = addrid;
	}
/*
	public Serializable getTheGeom() {
		return this.theGeom;
	}

	public void setTheGeom(Serializable theGeom) {
		this.theGeom = theGeom;
	}
*/
}
