package com.amsoftgroup.geospatial.dc.hibernate;

// Generated Jan 8, 2012 5:37:14 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Libraries generated by hbm2java
 */
@XmlRootElement
public class Libraries implements java.io.Serializable {

	private int gid;
	private Long objectid;
	private String gisId;
	private String name;
	private String address;
	private String phone;
	private String ssl;
	private String webUrl;
	private String type;
	private BigDecimal addressId;
	private String status;
	//private Serializable theGeom;

	public Libraries() {
	}

	public Libraries(int gid) {
		this.gid = gid;
	}

	public Libraries(int gid, Long objectid, String gisId, String name,
			String address, String phone, String ssl, String webUrl,
			String type, BigDecimal addressId, String status,
			Serializable theGeom) {
		this.gid = gid;
		this.objectid = objectid;
		this.gisId = gisId;
		this.name = name;
		this.address = address;
		this.phone = phone;
		this.ssl = ssl;
		this.webUrl = webUrl;
		this.type = type;
		this.addressId = addressId;
		this.status = status;
		//this.theGeom = theGeom;
	}

	public int getGid() {
		return this.gid;
	}

	public void setGid(int gid) {
		this.gid = gid;
	}

	public Long getObjectid() {
		return this.objectid;
	}

	public void setObjectid(Long objectid) {
		this.objectid = objectid;
	}

	public String getGisId() {
		return this.gisId;
	}

	public void setGisId(String gisId) {
		this.gisId = gisId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getSsl() {
		return this.ssl;
	}

	public void setSsl(String ssl) {
		this.ssl = ssl;
	}

	public String getWebUrl() {
		return this.webUrl;
	}

	public void setWebUrl(String webUrl) {
		this.webUrl = webUrl;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public BigDecimal getAddressId() {
		return this.addressId;
	}

	public void setAddressId(BigDecimal addressId) {
		this.addressId = addressId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
/*
	public Serializable getTheGeom() {
		return this.theGeom;
	}

	public void setTheGeom(Serializable theGeom) {
		this.theGeom = theGeom;
	}
*/
}
