package com.amsoftgroup.geospatial.dc.hibernate;

// Generated Jan 8, 2012 5:37:14 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Nationalparks generated by hbm2java
 */
@XmlRootElement
public class Nationalparks implements java.io.Serializable {

	private int gid;
	private Long objectid;
	private String gisId;
	private String name;
	private String alphaCode;
	private Integer parkCode;
	private String location;
	private String aquired;
	private Date transDc;
	private String source;
	private String reserve;
	private BigDecimal shapeArea;
	private BigDecimal shapeLen;
	//private Serializable theGeom;

	public Nationalparks() {
	}

	public Nationalparks(int gid) {
		this.gid = gid;
	}

	public Nationalparks(int gid, Long objectid, String gisId, String name,
			String alphaCode, Integer parkCode, String location,
			String aquired, Date transDc, String source, String reserve,
			BigDecimal shapeArea, BigDecimal shapeLen, Serializable theGeom) {
		this.gid = gid;
		this.objectid = objectid;
		this.gisId = gisId;
		this.name = name;
		this.alphaCode = alphaCode;
		this.parkCode = parkCode;
		this.location = location;
		this.aquired = aquired;
		this.transDc = transDc;
		this.source = source;
		this.reserve = reserve;
		this.shapeArea = shapeArea;
		this.shapeLen = shapeLen;
		//this.theGeom = theGeom;
	}

	public int getGid() {
		return this.gid;
	}

	public void setGid(int gid) {
		this.gid = gid;
	}

	public Long getObjectid() {
		return this.objectid;
	}

	public void setObjectid(Long objectid) {
		this.objectid = objectid;
	}

	public String getGisId() {
		return this.gisId;
	}

	public void setGisId(String gisId) {
		this.gisId = gisId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAlphaCode() {
		return this.alphaCode;
	}

	public void setAlphaCode(String alphaCode) {
		this.alphaCode = alphaCode;
	}

	public Integer getParkCode() {
		return this.parkCode;
	}

	public void setParkCode(Integer parkCode) {
		this.parkCode = parkCode;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getAquired() {
		return this.aquired;
	}

	public void setAquired(String aquired) {
		this.aquired = aquired;
	}

	public Date getTransDc() {
		return this.transDc;
	}

	public void setTransDc(Date transDc) {
		this.transDc = transDc;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getReserve() {
		return this.reserve;
	}

	public void setReserve(String reserve) {
		this.reserve = reserve;
	}

	public BigDecimal getShapeArea() {
		return this.shapeArea;
	}

	public void setShapeArea(BigDecimal shapeArea) {
		this.shapeArea = shapeArea;
	}

	public BigDecimal getShapeLen() {
		return this.shapeLen;
	}

	public void setShapeLen(BigDecimal shapeLen) {
		this.shapeLen = shapeLen;
	}

	/*
	public Serializable getTheGeom() {
		return this.theGeom;
	}

	public void setTheGeom(Serializable theGeom) {
		this.theGeom = theGeom;
	}
*/
}
