package com.amsoftgroup.geospatial.dc.hibernate;

// Generated Jan 8, 2012 5:37:14 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Neighborhoodcomposition generated by hbm2java
 */
@XmlRootElement
public class Neighborhoodcomposition implements java.io.Serializable {

	private int gid;
	private Double area;
	private Double perimeter;
	private Double dcCenTra;
	private Double dcCenT1;
	private Long pop90;
	private Long hunits90;
	private String tractbna;
	private Long pop;
	private Double hhUn80p;
	private Double tract;
	private Long f;
	private String z990Ct;
	private String tractbna1;
	private Double povrate;
	private Double povgroup;
	private Short weiss;
	private String nhoodComp;
	private BigDecimal shapeArea;
	private BigDecimal shapeLen;
	//private Serializable theGeom;

	public Neighborhoodcomposition() {
	}

	public Neighborhoodcomposition(int gid) {
		this.gid = gid;
	}

	public Neighborhoodcomposition(int gid, Double area, Double perimeter,
			Double dcCenTra, Double dcCenT1, Long pop90, Long hunits90,
			String tractbna, Long pop, Double hhUn80p, Double tract, Long f,
			String z990Ct, String tractbna1, Double povrate, Double povgroup,
			Short weiss, String nhoodComp, BigDecimal shapeArea,
			BigDecimal shapeLen, Serializable theGeom) {
		this.gid = gid;
		this.area = area;
		this.perimeter = perimeter;
		this.dcCenTra = dcCenTra;
		this.dcCenT1 = dcCenT1;
		this.pop90 = pop90;
		this.hunits90 = hunits90;
		this.tractbna = tractbna;
		this.pop = pop;
		this.hhUn80p = hhUn80p;
		this.tract = tract;
		this.f = f;
		this.z990Ct = z990Ct;
		this.tractbna1 = tractbna1;
		this.povrate = povrate;
		this.povgroup = povgroup;
		this.weiss = weiss;
		this.nhoodComp = nhoodComp;
		this.shapeArea = shapeArea;
		this.shapeLen = shapeLen;
		//this.theGeom = theGeom;
	}

	public int getGid() {
		return this.gid;
	}

	public void setGid(int gid) {
		this.gid = gid;
	}

	public Double getArea() {
		return this.area;
	}

	public void setArea(Double area) {
		this.area = area;
	}

	public Double getPerimeter() {
		return this.perimeter;
	}

	public void setPerimeter(Double perimeter) {
		this.perimeter = perimeter;
	}

	public Double getDcCenTra() {
		return this.dcCenTra;
	}

	public void setDcCenTra(Double dcCenTra) {
		this.dcCenTra = dcCenTra;
	}

	public Double getDcCenT1() {
		return this.dcCenT1;
	}

	public void setDcCenT1(Double dcCenT1) {
		this.dcCenT1 = dcCenT1;
	}

	public Long getPop90() {
		return this.pop90;
	}

	public void setPop90(Long pop90) {
		this.pop90 = pop90;
	}

	public Long getHunits90() {
		return this.hunits90;
	}

	public void setHunits90(Long hunits90) {
		this.hunits90 = hunits90;
	}

	public String getTractbna() {
		return this.tractbna;
	}

	public void setTractbna(String tractbna) {
		this.tractbna = tractbna;
	}

	public Long getPop() {
		return this.pop;
	}

	public void setPop(Long pop) {
		this.pop = pop;
	}

	public Double getHhUn80p() {
		return this.hhUn80p;
	}

	public void setHhUn80p(Double hhUn80p) {
		this.hhUn80p = hhUn80p;
	}

	public Double getTract() {
		return this.tract;
	}

	public void setTract(Double tract) {
		this.tract = tract;
	}

	public Long getF() {
		return this.f;
	}

	public void setF(Long f) {
		this.f = f;
	}

	public String getZ990Ct() {
		return this.z990Ct;
	}

	public void setZ990Ct(String z990Ct) {
		this.z990Ct = z990Ct;
	}

	public String getTractbna1() {
		return this.tractbna1;
	}

	public void setTractbna1(String tractbna1) {
		this.tractbna1 = tractbna1;
	}

	public Double getPovrate() {
		return this.povrate;
	}

	public void setPovrate(Double povrate) {
		this.povrate = povrate;
	}

	public Double getPovgroup() {
		return this.povgroup;
	}

	public void setPovgroup(Double povgroup) {
		this.povgroup = povgroup;
	}

	public Short getWeiss() {
		return this.weiss;
	}

	public void setWeiss(Short weiss) {
		this.weiss = weiss;
	}

	public String getNhoodComp() {
		return this.nhoodComp;
	}

	public void setNhoodComp(String nhoodComp) {
		this.nhoodComp = nhoodComp;
	}

	public BigDecimal getShapeArea() {
		return this.shapeArea;
	}

	public void setShapeArea(BigDecimal shapeArea) {
		this.shapeArea = shapeArea;
	}

	public BigDecimal getShapeLen() {
		return this.shapeLen;
	}

	public void setShapeLen(BigDecimal shapeLen) {
		this.shapeLen = shapeLen;
	}
/*
	public Serializable getTheGeom() {
		return this.theGeom;
	}

	public void setTheGeom(Serializable theGeom) {
		this.theGeom = theGeom;
	}
*/
}
