package com.amsoftgroup.geospatial.dc.hibernate;

// Generated Jan 8, 2012 5:37:14 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Placesofworship generated by hbm2java
 */
@XmlRootElement
public class Placesofworship implements java.io.Serializable {

	private int gid;
	private Long objectid;
	private String gisId;
	private String name;
	private String webUrl;
	private String religion;
	private String address;
	private Long addrid;
	//private Serializable theGeom;

	public Placesofworship() {
	}

	public Placesofworship(int gid) {
		this.gid = gid;
	}

	public Placesofworship(int gid, Long objectid, String gisId, String name,
			String webUrl, String religion, String address, Long addrid,
			Serializable theGeom) {
		this.gid = gid;
		this.objectid = objectid;
		this.gisId = gisId;
		this.name = name;
		this.webUrl = webUrl;
		this.religion = religion;
		this.address = address;
		this.addrid = addrid;
		//this.theGeom = theGeom;
	}

	public int getGid() {
		return this.gid;
	}

	public void setGid(int gid) {
		this.gid = gid;
	}

	public Long getObjectid() {
		return this.objectid;
	}

	public void setObjectid(Long objectid) {
		this.objectid = objectid;
	}

	public String getGisId() {
		return this.gisId;
	}

	public void setGisId(String gisId) {
		this.gisId = gisId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getWebUrl() {
		return this.webUrl;
	}

	public void setWebUrl(String webUrl) {
		this.webUrl = webUrl;
	}

	public String getReligion() {
		return this.religion;
	}

	public void setReligion(String religion) {
		this.religion = religion;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Long getAddrid() {
		return this.addrid;
	}

	public void setAddrid(Long addrid) {
		this.addrid = addrid;
	}
/*
	public Serializable getTheGeom() {
		return this.theGeom;
	}

	public void setTheGeom(Serializable theGeom) {
		this.theGeom = theGeom;
	}
*/
}
